// Rohy's terms of use: the default agreement, its limits, and the one parser
// both the server and the browser use to render it.
//
// Lives in server/shared because the client imports it too (the terms page
// renders the same text the server versions and snapshots on acceptance), and
// the Docker runtime stage copies server/ but not src/.
//
// EDIT THE DEFAULT TEXT AS A LEGAL DOCUMENT, NOT AS COPY. People put their name
// to it. If its meaning changes, the version an administrator publishes must
// change too: acceptance is keyed on the version, so a changed document under
// an unchanged version reads as already accepted by everyone who signed the old
// one. Modelled on chatoyon+'s agreement (chatoyon-plus/src/lib/license/
// defaultTerms.mjs); draft history in docs/design/rohy-terms-of-use-draft.md.

export const DEFAULT_TERMS_TITLE = 'Rohy – Learning Analytics Principles and Agreement';
export const DEFAULT_TERMS_VERSION = '1.0';

export const DEFAULT_TERMS_BODY = [
    "Before you begin using Rohy, we want to explain what it does with your data and the principles that govern how that data is handled.",
    "",
    "By continuing to use Rohy, you acknowledge that you have been informed about these principles.",
    "",
    "## 1. Purpose of the Application",
    "",
    "Rohy is a clinical simulation for learning. You talk to virtual patients, examine them, order tests and treatments, and discuss the case afterwards. The patients and the discussant are generated by artificial intelligence. They are for practice only and must never be used for decisions about real patients.",
    "",
    "The goal of Rohy is to enhance learning, teaching, and research on how clinical reasoning is learned.",
    "",
    "The application is designed to support learning and education, not to judge, rank, or define students.",
    "",
    "## 2. Why Data Is Collected",
    "",
    "Data is collected for three purposes only:",
    "",
    "- to give you and your educators feedback on your learning;",
    "- to improve Rohy and the way simulation is taught;",
    "- for research on learning.",
    "",
    "## 3. What Is Collected",
    "",
    "Rohy keeps a record of your simulation sessions, including your conversations with the characters and the actions you take in a case.",
    "",
    "With your permission, Rohy can also measure how you learn during a session, such as your engagement, your typing and your speech. This is entirely optional: it stays off until you turn it on, and you can turn it off at any time. All measurement happens in your own browser, and no video or audio recording is ever stored; only a summary of what was measured is kept. These measurements are estimates, not judgements of your knowledge, abilities or feelings.",
    "",
    "## 4. Our Commitments to You",
    "",
    "Your privacy is guaranteed. Your personal data will be protected in accordance with applicable Finnish law and the General Data Protection Regulation (GDPR).",
    "",
    "Learning analytics data will not be treated as an official record of your academic achievement or work and will not be used for assessment or grading.",
    "",
    "The application will not be used to profile students based on ability, gender, race, religion, socio-economic status, or other characteristics in ways that could result in discriminatory treatment.",
    "",
    "We recognise that learning analytics data can be incomplete and that analytical methods have limitations. Information generated by the application may therefore not provide a complete or accurate representation of your learning, circumstances, abilities, or needs.",
    "",
    "## 5. Your Choices",
    "",
    "Oyon measurement is your choice. It stays off unless you turn it on, and turning it off, or never turning it on, does not affect your access to Rohy or your academic assessment or standing.",
    "",
    "Where your data is used in a research study that requires your consent, you will be asked to provide that consent separately.",
    "",
    "## 6. Protection of Your Data",
    "",
    "Access to identifiable student data will be limited to authorised persons who have a legitimate need to access it, such as your educators and the research team.",
    "",
    "Anonymisation will be prioritised whenever data is processed and where anonymisation is feasible and appropriate.",
    "",
    "Non-anonymised data will not be shared with, transferred to, or otherwise handled by third parties, except where such processing is required or permitted by applicable law.",
    "",
    "Access to and processing of student data will be appropriately regulated, monitored, and subject to relevant ethical, legal, data protection, and privacy oversight.",
    "",
    "## 7. Use of Anonymised Data",
    "",
    "Anonymised data may be used to test, evaluate, develop, and improve Rohy.",
    "",
    "Anonymised data may also be used for research intended to improve learning, teaching, and clinical education.",
    "",
    "Where anonymised data is used for these purposes, appropriate measures will be taken to ensure that individuals cannot reasonably be re-identified.",
    "",
    "## 8. Transparency",
    "",
    "We will clearly communicate the purposes for which learning analytics is used and the limits of any actions based on it.",
    "",
    "Any significant changes to the way data is collected or used will be communicated, and you will be asked to accept the updated agreement.",
    "",
    "By continuing to use the application, you acknowledge that you have been informed about how learning analytics is used and the principles that govern the protection and handling of your data.",
    "",
].join('\n');

export const TERMS_TITLE_MAX = 200;
export const TERMS_BODY_MAX = 100_000;
export const TERMS_VERSION_MAX = 40;

/** Trim a version string; empty stays empty so the caller can fall back. */
export function normalizeTermsVersion(value) {
    return String(value ?? '').trim();
}

/** A human-readable problem with a version an admin typed, or null. */
export function termsVersionError(value) {
    const v = normalizeTermsVersion(value);
    if (!v) return 'Version is required';
    if (v.length > TERMS_VERSION_MAX) return `Version must be at most ${TERMS_VERSION_MAX} characters`;
    if (!/^[\w.\-+ ]+$/.test(v)) return 'Version may contain letters, digits, spaces, dots, dashes and plus signs only';
    return null;
}

/**
 * Parse the agreement's markdown subset into blocks:
 *   "## " heading → { type: 'heading', text }
 *   "- " lines    → { type: 'list', items: [text] }
 *   other lines   → { type: 'paragraph', text } (consecutive lines joined)
 * Inline `**bold**` is returned as segments by `inlineSegments`. Nothing else is
 * interpreted — the text is rendered as text, never as HTML.
 */
export function parseTermsBody(body) {
    const blocks = [];
    let paragraph = [];
    let list = null;
    const flush = () => {
        if (paragraph.length) blocks.push({ type: 'paragraph', text: paragraph.join(' ') });
        paragraph = [];
        if (list) blocks.push(list);
        list = null;
    };
    for (const raw of String(body ?? '').split(/\r?\n/)) {
        const line = raw.trim();
        if (!line) { flush(); continue; }
        if (line.startsWith('## ')) { flush(); blocks.push({ type: 'heading', text: line.slice(3).trim() }); continue; }
        if (/^[-*] /.test(line)) {
            if (paragraph.length) { blocks.push({ type: 'paragraph', text: paragraph.join(' ') }); paragraph = []; }
            if (!list) list = { type: 'list', items: [] };
            list.items.push(line.slice(2).trim());
            continue;
        }
        if (list) { blocks.push(list); list = null; }
        paragraph.push(line);
    }
    flush();
    return blocks;
}

/** Split text on `**bold**` into [{ text, bold }] segments. */
export function inlineSegments(text) {
    const out = [];
    const re = /\*\*(.+?)\*\*/g;
    let last = 0;
    let m;
    while ((m = re.exec(String(text ?? ''))) !== null) {
        if (m.index > last) out.push({ text: text.slice(last, m.index), bold: false });
        out.push({ text: m[1], bold: true });
        last = m.index + m[0].length;
    }
    if (last < String(text ?? '').length) out.push({ text: text.slice(last), bold: false });
    return out;
}
