// i18next bootstrap (I18N_PLAN.md §6).
//
// Loading strategy:
//   - English is EAGER (bundled): it is the global fallback, so a missing
//     Finnish key must render English synchronously — never a raw key, and
//     never a flash of keys while a chunk loads. Eager en also makes unit
//     tests deterministic without async init.
//   - Every other language (it/fi/sv/en-XA) is LAZY: vite code-splits each
//     locale JSON via import.meta.glob and the chunks load on first switch.
//     Students never download locales they don't use.
//
// ICU message format (i18next-icu) is on for ALL messages — Finnish/Swedish
// plural rules ("1 tulos / 2 tulosta") break naive `count === 1` string
// code, so plurals/selects in locale files use ICU syntax.
//
// Namespaces mirror student-facing component domains; en/<ns>.json is the
// canonical key set (i18next-parser keeps it in sync — npm run i18n:extract).

import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import ICU from 'i18next-icu';
import { LANGUAGES, DEFAULT_LANGUAGE } from './languages.js';

// The pseudo-locale is a QA tool, not a registry language: accented and
// lengthened English (generated by scripts/generate-pseudo-locale.mjs) that
// exposes hardcoded strings and layout truncation before paying for
// translation. Activate with ?pseudo=1 (handled in LanguageContext).
export const PSEUDO_LOCALE = 'en-XA';

const enModules = import.meta.glob('../locales/en/*.json', { eager: true });
const enResources = {};
for (const [path, mod] of Object.entries(enModules)) {
    const ns = path.match(/\/([\w-]+)\.json$/)[1];
    enResources[ns] = mod.default;
}

export const NAMESPACES = Object.keys(enResources);

i18n
    .use(ICU)
    .use(initReactI18next)
    .init({
        resources: { [DEFAULT_LANGUAGE]: enResources },
        lng: DEFAULT_LANGUAGE,
        fallbackLng: DEFAULT_LANGUAGE,
        supportedLngs: [...Object.keys(LANGUAGES), PSEUDO_LOCALE],
        // en-XA must not fall back to en-US-style regional stripping
        nonExplicitSupportedLngs: false,
        defaultNS: 'common',
        ns: NAMESPACES,
        interpolation: { escapeValue: false }, // React already escapes
        react: { useSuspense: false },
        returnEmptyString: false,
    });

// Non-eager glob: each locale file becomes its own chunk, imported on the
// first switch to that language. English is excluded — it's already in the
// eager bundle above (and double-matching it makes rollup warn that the
// dynamic import can't be split).
const lazyModules = import.meta.glob(['../locales/*/*.json', '!../locales/en/*.json']);

const loaded = new Set([DEFAULT_LANGUAGE]);

async function loadLanguage(lng) {
    if (loaded.has(lng)) return;
    const prefix = `../locales/${lng}/`;
    const imports = Object.entries(lazyModules)
        .filter(([path]) => path.startsWith(prefix))
        .map(async ([path, load]) => {
            const ns = path.match(/\/([\w-]+)\.json$/)[1];
            const mod = await load();
            i18n.addResourceBundle(lng, ns, mod.default, true, true);
        });
    await Promise.all(imports);
    loaded.add(lng);
}

/**
 * Switch the UI language, lazy-loading its locale files first. Unknown or
 * unloaded languages degrade to English via fallbackLng — never raw keys.
 * @param {string} lng  Registry code ('en', 'it', …) or PSEUDO_LOCALE.
 */
export async function setAppLanguage(lng) {
    try {
        await loadLanguage(lng);
    } catch (err) {
        console.error(`[i18n] Failed to load locale '${lng}', falling back to English:`, err);
    }
    await i18n.changeLanguage(lng);
}

export default i18n;
