// GENERATED by scripts/generate-stemi-ecg.mjs — do not edit by hand.
// The default STEMI case's arrival ECG (config.ecg). Regenerate with:
//   node scripts/generate-stemi-ecg.mjs

export const STEMI_V2_ECG = {
  "manifest": {
    "schema_version": "1.0.0",
    "id": "chest-pain-arrival-ecg",
    "title": "Arrival 12-lead ECG",
    "purpose": "Interpret the first 12-lead ECG of a man with ongoing chest pain, and decide what it means for the next ten minutes.",
    "difficulty": "advanced",
    "patient": {
      "age_years": 55,
      "sex": "male",
      "presentation": "A 55-year-old man with 45 minutes of central chest pain. Recorded on arrival in the emergency department.",
      "history": "Hypertension, type 2 diabetes, smoker.",
      "vitals": {
        "heart_rate_bpm": 92,
        "blood_pressure": "152/94",
        "respiratory_rate": 20,
        "oxygen_saturation_percent": 95
      }
    },
    "recordings": [
      {
        "id": "chest-pain-arrival-ecg-recording-1",
        "title": "Resting 12-lead ECG",
        "synthetic": true,
        "render_spec": {
          "engine_version": "1.0.0",
          "acquisition": {
            "duration_seconds": 10,
            "sample_rate_hz": 500,
            "paper_speed_mm_per_second": 25,
            "gain_mm_per_mv": 10,
            "rhythm_lead": "II",
            "placement": "standard_resting_12_lead"
          },
          "seed": 20261004,
          "rhythm": {
            "mode": "sinus",
            "ventricular_rate_bpm": 92,
            "atrial_rate_bpm": 92,
            "rr_jitter_fraction": 0.015,
            "pvc_every_n_beats": null
          },
          "intervals_ms": {
            "p_duration": 90,
            "pr": 160,
            "qrs": 90,
            "qt": 400
          },
          "morphology": {
            "axis_degrees": 60,
            "t_width_ms": 92,
            "delta_wave_mv": 0,
            "ventricular_scale": 1,
            "channels": {
              "I": {
                "p": 0.09177222981616737,
                "q": -0.045000000000000005,
                "r": 0.5500000000000002,
                "s": -0.11000000000000003,
                "st": 0.1,
                "t": 0.27647875144394013,
                "u": 0,
                "r_prime": 0,
                "pr_segment": 0
              },
              "II": {
                "p": 0.1593911516946793,
                "q": -0.09,
                "r": 1.1,
                "s": -0.22,
                "st": -0.1,
                "t": 0.3776769980790257,
                "u": 0,
                "r_prime": 0,
                "pr_segment": 0
              },
              "V1": {
                "p": 0.05,
                "q": -0.03,
                "r": 0.12100000000000001,
                "s": -0.8,
                "st": 0.18,
                "t": 0.1,
                "u": 0,
                "r_prime": 0,
                "pr_segment": 0
              },
              "V2": {
                "p": 0.08,
                "q": -0.03,
                "r": 0.24750000000000003,
                "s": -1,
                "st": 0.3,
                "t": 0.1875,
                "u": 0,
                "r_prime": 0,
                "pr_segment": 0
              },
              "V3": {
                "p": 0.1,
                "q": -0.03,
                "r": 0.85,
                "s": -0.75,
                "st": 0.34,
                "t": 0.35000000000000003,
                "u": 0,
                "r_prime": 0,
                "pr_segment": 0
              },
              "V4": {
                "p": 0.12,
                "q": -0.08,
                "r": 1.25,
                "s": -0.35,
                "st": 0.24,
                "t": 0.475,
                "u": 0,
                "r_prime": 0,
                "pr_segment": 0
              },
              "V5": {
                "p": 0.1,
                "q": -0.08,
                "r": 1.35,
                "s": -0.2,
                "st": 0.08,
                "t": 0.4,
                "u": 0,
                "r_prime": 0,
                "pr_segment": 0
              },
              "V6": {
                "p": 0.08,
                "q": -0.06,
                "r": 1.05,
                "s": -0.12,
                "st": 0.08,
                "t": 0.32,
                "u": 0,
                "r_prime": 0,
                "pr_segment": 0
              }
            }
          },
          "artifact": {
            "baseline_wander_mv": 0.012,
            "muscle_noise_mv": 0.003,
            "mains_noise_mv": 0,
            "mains_frequency_hz": 50
          }
        }
      }
    ],
    "activities": [
      {
        "id": "chest-pain-arrival-ecg-activity-1",
        "recording_id": "chest-pain-arrival-ecg-recording-1",
        "prompt": "Read this tracing systematically — rate, rhythm, axis, intervals, morphology — and say what it changes about what you do next.",
        "response_fields": [
          "rate",
          "rhythm",
          "axis",
          "intervals",
          "findings",
          "impression"
        ]
      }
    ],
    "provenance": {
      "synthetic": true,
      "source_kind": "library",
      "clinical_review": {
        "status": "pending",
        "reviewed_by": null,
        "reviewed_at": null,
        "notes": ""
      }
    }
  },
  "rubric": {
    "schema_version": "1.0.0",
    "case_id": "chest-pain-arrival-ecg",
    "activities": [
      {
        "activity_id": "chest-pain-arrival-ecg-activity-1",
        "expected": {
          "rate_range_bpm": [
            87,
            97
          ],
          "rhythm": "sinus",
          "axis": "normal",
          "interval_ranges_ms": {
            "pr": [
              140,
              180
            ],
            "qrs": [
              75,
              105
            ],
            "qt": [
              370,
              430
            ]
          },
          "finding_ids": [
            "sinus_rhythm",
            "st_elevation_anterior",
            "st_depression",
            "poor_r_wave_progression"
          ],
          "critical_finding_ids": [
            "st_elevation_anterior"
          ],
          "accepted_diagnoses": [
            "anterior acute injury pattern",
            "anterior stemi pattern",
            "anterior st-elevation myocardial infarction pattern"
          ]
        },
        "hints": [],
        "rationale": "Convex ST elevation V1–V4 (maximal V2–V3) with slight elevation in aVL and reciprocal ST depression in III and aVF: an anterior injury pattern from a proximal LAD occlusion. No Q waves yet, consistent with 45 minutes of symptoms.",
        "findings": [
          {
            "id": "rate",
            "text": "Sinus rhythm at about 92 per minute, normal axis, PR 160 ms, QRS 90 ms."
          },
          {
            "id": "st_elevation",
            "text": "ST elevation V1 to V4, maximal in V2 and V3 (about 3 mm), with slight elevation in aVL."
          },
          {
            "id": "reciprocal",
            "text": "Reciprocal ST depression in III and aVF."
          },
          {
            "id": "q_waves",
            "text": "No pathological Q waves yet; early loss of R-wave height in V1 and V2."
          }
        ]
      }
    ],
    "authoring_source": {
      "preset_id": "anterior_injury_pattern",
      "preset_version": "1.0.0"
    }
  }
};
