import { EMOTION_MODEL_HSE_B0_URL } from './cdnDefaults.js';

export const HSE_EMOTION_MTL_CONFIG = {
  id: 'hsemotion-enet-b0-8-va-mtl',
  modelName: 'enet_b0_8_va_mtl',
  modelVersion: 'hsemotion-onnx-0.3.1-source',
  modelUrl: EMOTION_MODEL_HSE_B0_URL,
  labels: ['anger', 'contempt', 'disgust', 'fear', 'happy', 'neutral', 'sad', 'surprise'],
  inputSize: 224,
  inputChannels: 3,
  inputName: 'input',
  outputName: null,
  inputScale: 1 / 255,
  colorOrder: 'BGR',
  mean: [0.485, 0.456, 0.406],
  std: [0.229, 0.224, 0.225],
  emotionOffset: 0,
  valenceIndex: 8,
  arousalIndex: 9,
  supportsValenceArousal: true,
  license: 'Apache-2.0 for hsemotion-onnx package',
  source: 'https://github.com/HSE-asavchenko/face-emotion-recognition',
  packageSource: 'https://pypi.org/project/hsemotion-onnx/',
  notes: [
    'EfficientNet-B0 multi-task AffectNet model from HSEmotionONNX.',
    'Outputs eight expression logits followed by valence and arousal.',
    'Browser canvas RGB is reordered to BGR to match the OpenCV-style package preprocessing.',
    'Experimental alternative profile; MobileViT remains the default.',
  ],
};
