-- 0049: the plugin job queue and the managed asset library (RPS-1 1.4).
--
-- The settings slot (0048) let an operator say WHETHER a plugin may import and
-- from where. These two tables are what an import actually is.
--
-- WHY A PERSISTED QUEUE AND NOT AN IN-PROCESS PROMISE
--
-- Tiling a whole-slide image is minutes of CPU against a multi-gigabyte file.
-- An in-memory job disappears on deploy, and the operator is left with a
-- half-written directory and no record that anything was ever asked for. A row
-- per job means a restart can resume, an admin can see a queue, and a job that
-- died mid-phase is distinguishable from one that was never started.
--
-- WHY THE JOB'S PHASE AND THE ASSET'S STATE ARE SEPARATE COLUMNS
--
-- They answer different questions and they outlive each other. `phase` is where
-- a RUNNING job is (downloading / probing / tiling / previewing) and is
-- meaningless once it finishes. `state` is what the LIBRARY holds, and it
-- survives every job: an asset stays 'ready' long after the job row is swept by
-- retention, and an asset in 'needs_calibration' has a completed job and is
-- still not usable. Collapsing them into one column forces a lie in one
-- direction or the other.
--
-- NEEDS_CALIBRATION IS A FIRST-CLASS STATE, NOT AN ERROR
--
-- OpenSlide exposes `openslide.objective-power` and `openslide.mpp-x/y` only
-- for vendors that wrote them. When they are absent the honest answer is "this
-- slide's optics are unknown", because a slide with unknown optics is NOT a
-- slide with default optics — every measurement a reader makes would be wrong
-- by an unknown factor, and 40x/0.25 is the most plausible guess and therefore
-- the most dangerous one. The author types the numbers once and the asset
-- becomes 'ready'.
--
-- Strictly additive: two new tables, referenced by nothing that exists.

CREATE TABLE IF NOT EXISTS plugin_jobs (
  id TEXT PRIMARY KEY,                    -- opaque, generated by the host
  tenant_id INTEGER NOT NULL,
  plugin_id TEXT NOT NULL,
  kind TEXT NOT NULL,                     -- the plugin's own job name, e.g. 'import_slide'
  -- queued → running → done | failed | cancelled. A job found 'running' at boot
  -- is a job whose process died; the runner requeues or fails it explicitly
  -- rather than leaving a row that claims work is in progress forever.
  state TEXT NOT NULL DEFAULT 'queued'
    CHECK (state IN ('queued', 'running', 'done', 'failed', 'cancelled')),
  phase TEXT,                             -- where a RUNNING job is; NULL otherwise
  progress INTEGER NOT NULL DEFAULT 0     -- 0-100, advisory only
    CHECK (progress BETWEEN 0 AND 100),
  payload TEXT NOT NULL DEFAULT '{}',     -- JSON; the plugin's own job arguments
  result TEXT,                            -- JSON; the plugin's own result
  error TEXT,
  attempts INTEGER NOT NULL DEFAULT 0,
  -- Set by a cancel request. Checked by the worker between phases rather than
  -- acted on immediately: killing vips mid-write leaves a partial pyramid, and
  -- a phase boundary is the one place the on-disk state is known.
  cancel_requested INTEGER NOT NULL DEFAULT 0,
  asset_id TEXT,                          -- the asset this job produces, if any
  created_by INTEGER REFERENCES users(id),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  started_at DATETIME,
  finished_at DATETIME
);

-- The queue read: oldest queued job for a plugin. Also serves the admin list.
CREATE INDEX IF NOT EXISTS idx_plugin_jobs_queue
  ON plugin_jobs(plugin_id, state, created_at);
CREATE INDEX IF NOT EXISTS idx_plugin_jobs_tenant
  ON plugin_jobs(tenant_id, plugin_id, created_at DESC);

CREATE TABLE IF NOT EXISTS plugin_assets (
  id TEXT PRIMARY KEY,                    -- the assetId; also the directory name
  tenant_id INTEGER NOT NULL,
  plugin_id TEXT NOT NULL,
  label TEXT NOT NULL,
  state TEXT NOT NULL DEFAULT 'importing'
    CHECK (state IN ('importing', 'ready', 'needs_calibration', 'failed')),
  -- Provenance. Kept for the life of the asset: "where did this slide come
  -- from and is it still the same bytes" is a question a teaching library has
  -- to be able to answer, and a digest is the only answer that survives the
  -- source host going away.
  source_url TEXT,
  source_sha256 TEXT,
  source_bytes INTEGER,
  -- Optics. NULL means the file did not carry them — see the header. Recorded
  -- separately from the objective the tiles were WRITTEN at, because a slide
  -- scanned at 40x and archived at 10x has both, and a measurement needs the
  -- one the pixels are actually at.
  native_objective REAL,
  native_mpp_x REAL,
  native_mpp_y REAL,
  tiled_objective REAL,
  width INTEGER,
  height INTEGER,
  disk_bytes INTEGER,
  error TEXT,
  created_by INTEGER REFERENCES users(id),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_plugin_assets_library
  ON plugin_assets(plugin_id, tenant_id, state, created_at DESC);
